INSERT INTO burgers (burger_name) VALUES ("Smokehouse Burger");
INSERT INTO burgers (burger_name) VALUES ("Bacon Cheddar Burger");
INSERT INTO burgers (burger_name) VALUES ("Grilled Chicken Avocado Burger");
INSERT INTO burgers (burger_name) VALUES ("Lambo");
INSERT INTO burgers (burger_name) VALUES ("Grilled Mahi Burger");
INSERT INTO burgers (burger_name) VALUES ("Sloppy Joe");
INSERT INTO burgers (burger_name) VALUES ("ChesseBurger");
INSERT INTO burgers (burger_name) VALUES ("Burger");
INSERT INTO burgers (burger_name) VALUES ("Eggplant Sausage Burger");
INSERT INTO burgers (burger_name) VALUES ("Fried Avocado Burger");
